### PR TITLE
Issue 154

### LINKED ISSUE #154: Add developer hint to type constraint violation error
Currently, constraints errors reports `<type> <constraint error message>`. It does not give much context for developers, we could either add value index or column name to `<constraint error message>`.

We can play around and add both or depending on how `insert` query is written. If it use column names like:
```sql
insert into table (col2, col1) values (32768, 0);
```
then error message could be like:
```
ERROR: smallint is out of range in col2 position
```
and if
```sql
insert into table values (32768, 0);
```
then error message could be like:
```
ERROR: smallint is out of range at 1 position
```

### PR DESCRIPTION
**Pull request by Tolledo**
Closes #154 

#### Description
Improved constrained violation error messages by returning `row_index` and `column_name` back to customer.

Example or error message:

```
smallint is out of range for column 'col1' at row 1
```
```
invalid input syntax for type smallint for column 'col1' at row 1: \"abc\"
```
```
value too long for type character for column 'col1' at row 1 (5)
```

#### Client output

e.g. for `psql`

```
psql (12.1, server 0.0.0)
Type "help" for help.

tolledo=> create schema SMOKE_TYPES;
CREATE SCHEMA
tolledo=> create table SMOKE_TYPES.NUMERIC_TYPES
tolledo-> (
tolledo(>     column_small_int        smallint,
tolledo(>     column_integer          integer,
tolledo(>     column_big_int          bigint
tolledo(> );
CREATE TABLE
tolledo=> insert into SMOKE_TYPES.NUMERIC_TYPES
tolledo-> values (-32768, -2147483648, -9223372036854775808);
INSERT 0 1
tolledo=> insert into SMOKE_TYPES.NUMERIC_TYPES
values (32768, -2147483648, -9223372036854775808);
ERROR:  smallint is out of range for column 'column_small_int' at row 1
```

### CODE REVIEW

File: src/protocol/src/lib.rs [hunk 1]
```diff
@@ -422,50 +422,50 @@ mod tests {
...
             let mut builder = QueryErrorBuilder::new();
-            builder.string_length_mismatch(PostgreSqlType::Char, 5);
+            builder.string_length_mismatch(PostgreSqlType::Char, 5, "col1".to_string(), 1);
             assert_eq!(
                 QueryResultMapper::map(Err(builder.build())),
                 vec![Message::ErrorResponse(
                     Some("ERROR"),
                     Some("22026"),
-                    Some("value too long for type character(5)".to_owned())
+                    Some("value too long for type character for column 'col1' at row 1 (5)".to_owned())
```
Comment (alex-dukhno) [inline src/protocol/src/lib.rs:468]: Can we have like in suggestion below? I think type name and its length is better to be together.
```suggestion
                    Some("value too long for type character(5) for column 'col1' at row 1".to_owned())
```

File: src/storage/src/frontend/mod.rs [hunk 2]
```diff
@@ -224,25 +223,18 @@ impl<P: BackendStorage> FrontendStorage<P> {
...
                         }
                     }
                 }
 
-                // if there was an error then exit the loop.
-                if constraint_error {
-                    break;
+                if !errors.is_empty() {
+                    // In SQL indexes start from 1, not 0.
+                    return Ok(Err(OperationOnTableError::ConstraintViolations(errors, row_index + 1)));
```
Comment (alex-dukhno) [inline src/storage/src/frontend/mod.rs:232]: 👍
