### PR TITLE
Check insert expressions

### LINKED ISSUE #71: handle error when user is trying to insert into a table more values than it has columns
SQL to reproduce:
```sql
create schema schema_name;
create table schema_name.table_name (column_in_table smallint);
insert into schema_name.table_name values (1, 2);
```

Expected result in `psql`:
```
ERROR:  INSERT has more expressions than target columns
```
additionally print line with the error like:
```
LINE 1: insert into empty values(1);
```

Actual result:
```
insert into schema_name.table_name values (1, 2);
INSERT 0 1
```

`storage/src/frontend/mod.rs` method
```rust
    pub fn insert_into(
        &mut self,
        schema_name: &str,
        table_name: &str,
        values: Vec<Vec<String>>,
    ) -> SystemResult<Result<(), OperationOnTableError>> {
```
does not check the number of columns in a table

### PR DESCRIPTION
**Pull request by AndrewBregger**
Closes #71

This pull request adds a check that checks whether there are enough target columns for the number of insert expressions. Another addition is handling when this error occurs. 

Current behavior:
```
=> create schema test1;                  
CREATE SCHEMA                                          
=> create table test1.foo (a int, b int);
CREATE TABLE                                                         
=> insert into test1.foo values (1,3,4); 
INSERT 0 1                                             
=> select * from test1.foo;              
 a | b                                                 
---+---                                                
 1 | 2                                                 
 1 | 3                                                 
(2 rows)                                               
```

Expected behavior:
```
postgres=# insert into foo values (1, 5, 3);
ERROR:  INSERT has more expressions than target columns
```

New behavior:
```
=> insert into test1.foo values(1,3,4);
ERROR:  INSERT has more expressions than target columns
```

### CODE REVIEW

File: src/storage/src/frontend/mod.rs [hunk 1]
```diff
@@ -183,7 +183,13 @@ impl<P: BackendStorage> FrontendStorage<P> {
 
         let mut to_write: Vec<Row> = vec![];
         let mut errors = HashMap::new();
+        let mut operation_error = None;
         for row in rows {
+            if row.len() > all_columns.len() {
+                operation_error = Some(OperationOnTableError::InsertTooManyExpressions);
+                break;
```
Comment (alex-dukhno) [inline src/storage/src/frontend/mod.rs:190]: I think you need to `return Ok(Err(OperationOnTableError::InsertTooManyExpressions))` otherwise you could select data out of table despite the error during an insertion.

File: src/storage/src/frontend/tests/queries/insert.rs [hunk 2]
```diff
@@ -241,6 +241,62 @@ fn insert_row_into_table(mut storage: PersistentStorage) {
...
+        storage
+            .insert_into(
+                "schema_name",
+                "table_name",
+                columns,
+                vec![vec!["1".to_owned(), "2".to_owned(), "3".to_owned(), "4".to_owned()]],
+            )
+            .expect("no system errors"),
+        Err(OperationOnTableError::InsertTooManyExpressions)
+    )
```
Comment (alex-dukhno) [inline src/storage/src/frontend/tests/queries/insert.rs:269]: Could you please add `assert_eq` with `storage.select_all` invocation to test that nothing was inserted? and also in the `insert_too_many_expressions_labeled`.

File: src/storage/src/frontend/mod.rs (hunk 1 above)
Comment (AndrewBregger) [reply src/storage/src/frontend/mod.rs:190]: I agree. However, when I did it that way I was getting this error when the table or schema didn't exist (all_columns is empty). It might be better to check if the table or schema exist before processing the rows.

File: src/storage/src/frontend/tests/queries/insert.rs (hunk 2 above)
Comment (AndrewBregger) [reply src/storage/src/frontend/tests/queries/insert.rs:269]: Sure, I didn't think about that.

File: src/storage/src/frontend/mod.rs (hunk 1 above)
Comment (alex-dukhno) [reply src/storage/src/frontend/mod.rs:190]: Ah, I see. Seems like we need to introduce changes to backend storage ... My previous assumption that database can live without `"system.tables"` table (where list of tables is stored) does not hold anymore.
Can you please add `BackendStorage::is_table_exists(&self, namespace: &str, object_name: &str) -> bool` function and call it before `self.persistent.write`?
I will have a look how we can improve situation to work with the storage
