### PR TITLE
 Handling named columns insertion

### LINKED ISSUE #103: Handling named columns insertion
To align `insert_into` and `update_all` from `FrontendStorage` methods signature which could allow refactoring of the storage we need to implement named insert.

Query to reproduce:
```
create schema SMOKE_QUERIES;

create table SMOKE_QUERIES.VALIDATION_TABLE (column_1 smallint, column_2 smallint, column_3 smallint);

insert into SMOKE_QUERIES.VALIDATION_TABLE (column_1, column_2, column_3) values (1, 2, 3);
```

Expected result:
```
INSERT 0 <number of rows>
```

### PR DESCRIPTION
**Pull request by silathdiir**
Fixes #103 

```
psql (12.1, server 0.0.0)
Type "help" for help.

xxx=> create schema schema_name;
CREATE SCHEMA
xxx=> create table schema_name.table_name (col1 smallint, col2 smallint, col3 smallint);
CREATE TABLE
xxx=> insert into schema_name.table_name (col3, col2, col1) values (1, 2, 3);
INSERT 0 1
xxx=> insert into schema_name.table_name (col3, col2, col1) values (4, 5, 6);
INSERT 0 1
xxx=> select * from schema_name.table_name;
 col1 | col2 | col3
------+------+------
    3 |    2 |    1
    6 |    5 |    4
(2 rows)
```

#### 1. Sets the default value or NULL for the missing columns of this inserting operation.

Our current implementation: I sets an integer `0` for the default value.

```
xxx=> create schema schema_name;
CREATE SCHEMA
xxx=> create table schema_name.table_name (col1 smallint, col2 smallint, col3 smallint);
CREATE TABLE
xxx=> insert into schema_name.table_name (col3, col2) values (1, 2);
INSERT 0 1
xxx=> select * from schema_name.table_name;
 col1 | col2 | col3
------+------+------
    0 |    2 |    1
(1 row)
```

PostgreSQL:

```
xxx=# insert into schema_name.table_name (col3, col2) values (1, 2);
INSERT 0 1
xxx=# select * from schema_name.table_name;
 col1 | col2 | col3
------+------+------
      |    2 |    1
(1 row)
```

#### 2. Handles the error if the counts of named columns and values are not equal.

Our current implementation: Same as above.

```
xxx=> insert into schema_name.table_name (col3, col2) values (1);
INSERT 0 1
xxx=> select * from schema_name.table_name;
 col1 | col2 | col3
------+------+------
    0 |    0 |    1
(1 row)

xxx=> insert into schema_name.table_name (col3) values (1, 2);
INSERT 0 1
xxx=> select * from schema_name.table_name;
 col1 | col2 | col3
------+------+------
    0 |    0 |    1
    0 |    0 |    1
(2 rows)
```

PostgreSQL:

```
xxx=# insert into schema_name.table_name (col3, col2) values (1);
ERROR:  INSERT has more target columns than expressions
LINE 1: insert into schema_name.table_name (col3, col2) values (1);

xxx=# insert into schema_name.table_name (col3) values (1, 2);
ERROR:  INSERT has more expressions than target columns
LINE 1: insert into schema_name.table_name (col3) values (1, 2);
```

### CODE REVIEW

**Comment by alex-dukhno** [comment]
Thanks for the PR and report about issues! I'll have a look soon.

File: src/sql_engine/src/lib.rs [hunk 1]
```diff
@@ -151,8 +154,23 @@ impl<P: BackendStorage> Handler<P> {
                                 .collect()
                         })
                         .collect();
-                    let len = to_insert.len();
-                    match (self.storage.lock().unwrap()).insert_into(&schema_name, &name, to_insert)? {
+
+                    let specified_columns = if columns.is_empty() {
```
Comment (alex-dukhno) [inline src/sql_engine/src/lib.rs:158]: This is more a question rather than I am asking for a changes. Have you considered to pass empty `Vec<String>` for column names?

Why I am asking is that I think `insert` and `update` probably, might be, possibly use similar logic.
For example:
`update_all` requires `Vec<(String, String)>` as one of a params, which is list of (`column name`, `column value`)
`insert_into` also could be changed to accept `Vec<(String, String)>` as list of (`column name`, `column value`)
by:
1) constructing it if user provide list of column names
2) reading column names in `sql_engine` as it's done for `select * from table` query and combining it with user provided values

WDYT?

File: src/storage/src/frontend/mod.rs [hunk 2]
```diff
@@ -155,21 +155,61 @@ impl<P: BackendStorage> FrontendStorage<P> {
...
+                };
+
                 let mut to_write: Vec<Row> = vec![];
                 let mut errors = HashMap::new();
                 for row in rows {
                     let key = self.key_id_generator.to_be_bytes().to_vec();
-                    let mut record = vec![];
+
+                    // TODO: The default value or NULL should be initialized for SQL types of all columns.
+                    let mut record = vec![vec![0, 0]; all_columns.len()];
```
Comment (alex-dukhno) [inline src/storage/src/frontend/mod.rs:205]: Why `vec![0, 0]` and not `vec![]` or `vec![0]`?

File: src/storage/src/frontend/tests/mod.rs [hunk 3]
```diff
@@ -69,12 +69,19 @@ fn insert_into<P: backend::BackendStorage>(
     schema_name: &str,
     table_name: &str,
     values: Vec<&str>,
+    columns: Option<Vec<&str>>,
 ) {
+    let columns = match columns {
+        Some(cols) => Some(cols.into_iter().map(ToOwned::to_owned).collect()),
+        None => None,
+    };
```
Comment (alex-dukhno) [inline src/storage/src/frontend/tests/mod.rs:77]: Consider, using `Optional::map` here, like:
```rust
columns.map(|cols| cols.into_iter().map(ToOwned::to_owned).collect())
```

File: src/sql_engine/src/lib.rs (hunk 1 above)
Comment (silathdiir) [reply src/sql_engine/src/lib.rs:158]: Yes. I think you are right. I will try to fix passing into a parameter of type `Vec<String, String>` like `update_all`. Thanks.

File: src/storage/src/frontend/mod.rs (hunk 2 above)
Comment (silathdiir) [reply src/storage/src/frontend/mod.rs:205]: I am sorry that I have not looked into the details. I tried to use `vec![]` and `vec![0]`, the `insert` operation succeeded, but the next `select` crashed. Below is the steps and crash log, I will look into it and update the PR.

```
xxx=> create schema schema_name;
CREATE SCHEMA
xxx=> create table schema_name.table_name (col1 smallint, col2 smallint, col3 smallint);
CREATE TABLE
xxx=> insert into schema_name.table_name (col3, col2) values (1, 2);
INSERT 0 1
asongala=> select * from schema_name.table_name;
```

For `vec![]`:

```
LEN = 21
PARAMS = b"client_encoding\0UTF8\0"
LEN = 26
PARAMS = b"S\0\0\0\x19client_encoding\0UTF8\0"
LEN = 14
PARAMS = b"DateStyle\0DMY\0"
LEN = 19
PARAMS = b"S\0\0\0\x12DateStyle\0DMY\0"
thread 'main' panicked at 'index 2 out of range for slice of length 0', src/sql_types/src/lib.rs:102:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

For `vec![0]`:

```
LEN = 21
PARAMS = b"client_encoding\0UTF8\0"
LEN = 26
PARAMS = b"S\0\0\0\x19client_encoding\0UTF8\0"
LEN = 14
PARAMS = b"DateStyle\0DMY\0"
LEN = 19
PARAMS = b"S\0\0\0\x12DateStyle\0DMY\0"
thread 'main' panicked at 'index 2 out of range for slice of length 1', src/sql_types/src/lib.rs:102:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Comment (alex-dukhno) [reply src/storage/src/frontend/mod.rs:205]: Thanks for posting errors. I got why it fails. This is because it assumes non null values. I hardcoded the size of possible data in storage here
https://github.com/alex-dukhno/database/blob/master/src/sql_types/src/lib.rs#L102.

I think we handle it when introducing `NOT NULL` constraint in #25 or #26

File: src/sql_engine/src/lib.rs (hunk 1 above)
Comment (silathdiir) [reply src/sql_engine/src/lib.rs:158]: Hi @alex-dukhno , I was working on fixing this, but it seems that `insert_into` could not unify with `update_all`. Since `insert_into` could insert multiple rows once. I thought if I could pass into the type of `Vec<Vec<String, String>>` (Multiple rows and each row including Column and Value). But it causes resolving column index for multiple times in `storage`.

So I try to fix it by passing into an empty column if no column specified. What's your opinion?

File: src/storage/src/frontend/tests/mod.rs (hunk 3 above)
Comment (silathdiir) [reply src/storage/src/frontend/tests/mod.rs:77]: `Option<Vec<String>>` is replaced with `Vec<String>`. So it is resolved.

File: src/sql_engine/src/lib.rs (hunk 1 above)
Comment (silathdiir) [reply src/sql_engine/src/lib.rs]: Hi @alex-dukhno , I updated the signature of function `insert_into` as below, and passed into an empty Vec if no column specified.

Please fell free to add your comments. I could not confirm if it is the best solution. Thanks.

```
    pub fn insert_into(
        &mut self,
        schema_name: &str,
        table_name: &str,
        columns: Vec<String>,
        rows: Vec<Vec<String>>,
    ) -> SystemResult<Result<(), OperationOnTableError>> {
```

File: src/storage/src/frontend/mod.rs (hunk 2 above)
Comment (silathdiir) [reply src/storage/src/frontend/mod.rs:202]: Hi @alex-dukhno , should I try to fix it in another PR?

**Comment by alex-dukhno** [comment]
Thanks for the PR
